services:
  postgres:
    image: postgres:15-alpine
    container_name: carmap-db
    environment:
      POSTGRES_DB: carmap_db
      POSTGRES_USER: carmap_user
      POSTGRES_PASSWORD: carmap_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: carmap-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/carmap_db
      SPRING_DATASOURCE_USERNAME: carmap_user
      SPRING_DATASOURCE_PASSWORD: carmap_pass
      JWT_SECRET: ${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - postgres

volumes:
  pgdata:
