spring:
  application:
    name: car-map
  datasource:
    url: jdbc:postgresql://localhost:5433/carmap_db
    username: carmap_user
    password: carmap_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=60s
logging:
  level:
    org.springframework.cache: DEBUG
server:
  servlet:
    session:
      cookie:
        max-age: 0
      timeout: 0
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 86400000 # 1 день